import type { Metadata } from "next";
import "@/styles/globals.css";
import vazirFont from "@/constants/localFont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`antialiased ${vazirFont.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
